**para el dataser https://github.com/owid/covid-19-data/blob/master/public/data/owid-covid-data.csv**

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import os
import warnings

# Ocultar advertencias para mantener el notebook limpio
warnings.filterwarnings('ignore')

# Crear directorios necesarios si no existen
os.makedirs("../data", exist_ok=True)
os.makedirs("../results", exist_ok=True)

In [2]:
import requests
url = "https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/owid-covid-data.csv"

response = requests.get(url)

if response.status_code == 200:
    with open("../data/owid-covid-data.csv", "wb") as f:
        f.write(response.content)
    print("Archivo descargado exitosamente en '../data/owid-covid-data.csv'")
else:
    print(f"Error al descargar el archivo. Código de estado: {response.status_code}")

Archivo descargado exitosamente en '../data/owid-covid-data.csv'

In [2]:
df =pd.read_csv("../data/owid-covid-data.csv",usecols=["location", "date", "total_cases", "new_cases", "total_deaths", "population"])
df['date'] = pd.to_datetime(df['date'])
df.head()

      location       date  total_cases  new_cases  total_deaths  population
0  Afghanistan 2020-01-05          0.0        0.0           0.0    41128772
1  Afghanistan 2020-01-06          0.0        0.0           0.0    41128772
2  Afghanistan 2020-01-07          0.0        0.0           0.0    41128772
3  Afghanistan 2020-01-08          0.0        0.0           0.0    41128772
4  Afghanistan 2020-01-09          0.0        0.0           0.0    41128772

In [8]:
# ¿Cuántos valores nulos hay?
print("Valores nulos por columna:")
display(df.isnull().sum())

# Rango de fechas
print("Rango de fechas:")
display(df['date'].min(), df['date'].max())

# informacion de las columnas
print("Información de las columnas:")
display(df.info())

# cantoidad de paises
print("Cantidad de países únicos:")
display(len(df['location'].unique()))

Valores nulos por columna:

location            0
date                0
total_cases     17631
new_cases       19276
total_deaths    17631
population          0
dtype: int64

Rango de fechas:

Timestamp('2020-01-01 00:00:00')

Timestamp('2024-08-14 00:00:00')

Información de las columnas:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 429435 entries, 0 to 429434
Data columns (total 6 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   location      429435 non-null  object
 1   date          429435 non-null  datetime64[ns]
 2   total_cases   411804 non-null  float64
 3   new_cases     410159 non-null  float64
 4   total_deaths  411804 non-null  float64
 5   population    429435 non-null  int64
dtypes: datetime64[ns](1), float64(3), int64(1), object(1)
memory usage: 19.7+ MB

None

Cantidad de países únicos:

255

In [ ]:
df_clean=df.copy()
# Rellenar con el anterior para total_cases y total_deaths
df_clean['total_cases'] = df_clean.groupby('location')['total_cases'].ffill().fillna(0)
df_clean['total_deaths'] = df_clean.groupby('location')['total_deaths'].ffill().fillna(0)

# Rellenar con cero para new_cases
df_clean['new_cases'] = df_clean['new_cases'].fillna(0)



# Verificar
print(df_clean.isnull().sum())

location        0
date            0
total_cases     0
new_cases       0
total_deaths    0
population      0
dtype: int64

In [17]:
display(df_clean[df_clean['location'] == 'Europe'].sort_values(by=['date']))

       location       date  total_cases  new_cases  total_deaths  population
118569   Europe 2020-01-05          1.0        1.0           3.0   744807803
118570   Europe 2020-01-06          1.0        0.0           3.0   744807803
118571   Europe 2020-01-07          1.0        0.0           3.0   744807803
118572   Europe 2020-01-08          1.0        0.0           3.0   744807803
118573   Europe 2020-01-09          1.0        0.0           3.0   744807803
...         ...        ...          ...        ...           ...         ...
120248   Europe 2024-08-10  252916868.0        0.0     2102483.0   744807803
120249   Europe 2024-08-11  252916868.0        0.0     2102483.0   744807803
120250   Europe 2024-08-12  252916868.0        0.0     2102483.0   744807803
120251   Europe 2024-08-13  252916868.0        0.0     2102483.0   744807803
120252   Europe 2024-08-14  252916868.0        0.0     2102483.0   744807803

[1684 rows x 6 columns]